/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function check(args: NapiCheckArgs): any

export declare function diff(args: NapiDiffArgs): any

export declare function export(args: NapiExportArgs): any

export declare function fmt(args: NapiFmtArgs): any

export declare function lint(args: NapiPackageArgs): any

export interface NapiCheckArgs {
  workspace: string
  package?: string
}

export interface NapiDiffArgs {
  before: string
  after: string
}

export interface NapiExportArgs {
  package: string
  /** `"json-schema"` (default) or `"openapi"`. */
  format?: string
  /**
   * When set, write the schema to this file instead of stdout. The
   * CLI verb writes the file AND prints a confirmation; we capture
   * only the JSON envelope.
   */
  out?: string
}

export interface NapiFmtArgs {
  package: string
  /** `--check`: exit 1 if the file would change; do not write. */
  check?: boolean
  /** `--stdout`: print the formatted source instead of writing it. */
  stdout?: boolean
}

export interface NapiPackageArgs {
  package: string
}

export interface NapiRenderArgs {
  package: string
  inputs?: string
  out: string
  dryRun?: boolean
  strict?: boolean
  offline?: boolean
}

export interface NapiWorkspaceArgs {
  workspace: string
}

export declare function render(args: NapiRenderArgs): any

export declare function tree(args: NapiWorkspaceArgs): any

export declare function verify(args: NapiWorkspaceArgs): any

/**
 * Crate version baked at compile time. Cheap sanity check the SDK's
 * loader runs after `require()` to confirm it loaded the real addon.
 */
export declare function version(): string

export declare function whoami(): any
