/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function check(args: NapiCheckArgs): any

export declare function diff(args: NapiDiffArgs): any

export declare function export(args: NapiExportArgs): any

export declare function fmt(args: NapiFmtArgs): any

export declare function inspect(args: NapiInspectArgs): any

export declare function lint(args: NapiPackageArgs): any

export interface NapiCheckArgs {
  workspace: string
  package?: string
}

export interface NapiDiffArgs {
  before: string
  after: string
}

export interface NapiExportArgs {
  package: string
  /** `"json-schema"` (default) or `"openapi"`. */
  format?: string
  /**
   * When set, write the schema to this file instead of stdout. The
   * CLI verb writes the file AND prints a confirmation; we capture
   * only the JSON envelope.
   */
  out?: string
}

export interface NapiFmtArgs {
  package: string
  /** `--check`: exit 1 if the file would change; do not write. */
  check?: boolean
  /** `--stdout`: print the formatted source instead of writing it. */
  stdout?: boolean
}

export interface NapiInspectArgs {
  /**
   * On-disk Package directory or `package.k`. Mutually exclusive
   * with `tarball`.
   */
  package?: string
  /**
   * `.tar.gz` Package artifact (e.g. from `akua pack`). Mutually
   * exclusive with `package`.
   */
  tarball?: string
}

export interface NapiPackageArgs {
  package: string
}

export interface NapiRenderArgs {
  package: string
  inputs?: string
  out: string
  dryRun?: boolean
  strict?: boolean
  offline?: boolean
  /**
   * Wall-clock cap (Go duration, e.g. `"30s"`, `"5m"`). Maps to
   * the universal `--timeout` flag; on the SDK side, exposed as
   * `RenderOptions.timeout`.
   */
  timeout?: string
  /**
   * Hard cap on `pkg.render` composition depth. `BudgetSnapshot`
   * default (16) when omitted.
   */
  maxDepth?: number
}

export interface NapiWorkspaceArgs {
  workspace: string
}

export declare function render(args: NapiRenderArgs): any

/**
 * Render a Package and return the multi-document YAML directly,
 * bypassing the on-disk write + summary envelope. Mirrors
 * `akua render --stdout`. The SDK uses this for `renderSource()`
 * where the caller wants raw YAML, not a `RenderSummary`.
 */
export declare function renderToYaml(args: NapiRenderArgs): string

export declare function tree(args: NapiWorkspaceArgs): any

export declare function verify(args: NapiWorkspaceArgs): any

/**
 * Routes through `verbs::version::run` so the JSON envelope stays
 * byte-stable with the CLI (`akua version --json`). Picking up
 * future fields the verb adds is automatic — no per-binding shape
 * drift like a `String`-only return would invite.
 */
export declare function version(): any

export declare function whoami(): any
