apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-greeting
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  greeting: {{ .Values.greeting | quote }}
  replicas: {{ .Values.replicas | quote }}
  
