//! helmfile engine — runs `helmfile template` against a user-authored
//! `helmfile.yaml`, captures the concatenated Kubernetes YAML, and wraps it
//! as a static Helm chart dir.
//!
//! Source shape:
//!
//! ```yaml
//! sources:
//!   - id: stack
//!     engine: helmfile
//!     chart:
//!       repoUrl: file://./helmfile.yaml    # path to the helmfile
//!       targetRevision: 0.1.0              # chart version for the output
//! ```
//!
//! Same early-binding model as the KCL engine: the chart that ships contains
//! pre-rendered manifests under `templates/`. Customers cannot `--set`
//! values at deploy time for helmfile-engine sources.
//!
//! Requires `helmfile` and `helm` on `$PATH`. Pin helmfile via `mise`.
//!
//! Note: helmfile templating is **not deterministic** by default — it
//! supports `exec`, env reads, `now`, etc. When used inside Akua, avoid
//! those functions or your chart's OCI digest will differ per build.

use std::path::PathBuf;
use std::process::Command;

use super::{Engine, EngineError, PrepareContext, PreparedSource};
use crate::source::HelmSource;
use crate::umbrella::ChartYaml;

#[derive(Debug, Clone, Default)]
pub struct HelmfileEngine;

impl Engine for HelmfileEngine {
    fn name(&self) -> &'static str {
        "helmfile"
    }

    fn prepare(
        &self,
        source: &HelmSource,
        ctx: &PrepareContext<'_>,
    ) -> Result<PreparedSource, EngineError> {
        let helmfile_path = resolve_helmfile_path(source)?;
        let source_id = source
            .id
            .clone()
            .unwrap_or_else(|| "helmfile-source".to_string());
        let chart_dir = ctx.work_dir.join(&source_id);
        let templates_dir = chart_dir.join("templates");

        std::fs::create_dir_all(&templates_dir).map_err(|e| EngineError::Write {
            engine: "helmfile",
            path: templates_dir.clone(),
            source: e,
        })?;

        let output = Command::new("helmfile")
            .arg("--file")
            .arg(&helmfile_path)
            .arg("template")
            .output()
            .map_err(|source| EngineError::Spawn {
                engine: "helmfile",
                cmd: format!("helmfile --file {} template", helmfile_path.display()),
                source,
            })?;

        if !output.status.success() {
            return Err(EngineError::CliFailed {
                engine: "helmfile",
                cmd: "helmfile template".to_string(),
                status: output.status.code().unwrap_or(-1),
                stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
            });
        }

        write(templates_dir.join("rendered.yaml"), &output.stdout)?;

        let chart_yaml = ChartYaml {
            api_version: "v2".to_string(),
            name: source_id,
            version: source.chart.target_revision.clone(),
            description: Some("Auto-generated by akua from a helmfile source".to_string()),
            chart_type: Some("application".to_string()),
            dependencies: Vec::new(),
        };
        let chart_yaml_bytes =
            serde_yaml::to_string(&chart_yaml).expect("ChartYaml serializes to YAML");
        write(chart_dir.join("Chart.yaml"), chart_yaml_bytes.as_bytes())?;

        Ok(PreparedSource::LocalChart(chart_dir))
    }
}

fn resolve_helmfile_path(source: &HelmSource) -> Result<PathBuf, EngineError> {
    let raw = if !source.chart.repo_url.is_empty() {
        source.chart.repo_url.as_str()
    } else if let Some(p) = source.chart.path.as_deref() {
        p
    } else {
        return Err(EngineError::MissingField {
            engine: "helmfile",
            source_id: source.id.clone().unwrap_or_default(),
            field: "chart.repoUrl or chart.path (helmfile.yaml path)",
        });
    };
    let stripped = raw.strip_prefix("file://").unwrap_or(raw);
    Ok(PathBuf::from(stripped))
}

fn write(path: PathBuf, bytes: &[u8]) -> Result<(), EngineError> {
    std::fs::write(&path, bytes).map_err(|e| EngineError::Write {
        engine: "helmfile",
        path,
        source: e,
    })
}

pub(crate) static HELMFILE_ENGINE: HelmfileEngine = HelmfileEngine;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::ChartRef;

    #[test]
    fn missing_entrypoint_errors() {
        let tmp = tempfile::tempdir().unwrap();
        let s = HelmSource {
            id: Some("empty".to_string()),
            engine: Some("helmfile".to_string()),
            chart: ChartRef {
                repo_url: "".to_string(),
                chart: None,
                target_revision: "0.1.0".to_string(),
                path: None,
            },
            values: None,
        };
        let ctx = PrepareContext {
            work_dir: tmp.path(),
        };
        let err = HelmfileEngine.prepare(&s, &ctx).unwrap_err();
        assert!(matches!(
            err,
            EngineError::MissingField {
                engine: "helmfile",
                ..
            }
        ));
    }
}
