//! helmfile engine — runs `helmfile template` against a user-authored
//! `helmfile.yaml` and wraps the rendered YAML as a static Helm chart.
//!
//! Source shape:
//!
//! ```yaml
//! sources:
//!   - name: stack
//!     helmfile:
//!       path: ./helmfile.yaml
//!       version: 0.1.0
//! ```
//!
//! Requires `helmfile` and `helm` on `$PATH`. Pin via `mise`.
//!
//! Note: helmfile templating is **not deterministic** by default — it
//! supports `exec`, env reads, `now`, etc. When used inside Akua, avoid
//! those functions or the chart's OCI digest will differ per build.

use std::path::PathBuf;
use std::process::Command;

use super::{Engine, EngineError, PrepareContext, PreparedSource};
use crate::source::Source;
use crate::umbrella::ChartYaml;

pub const ENGINE_NAME: &str = "helmfile";

#[derive(Debug, Clone, Default)]
pub struct HelmfileEngine;

impl Engine for HelmfileEngine {
    fn name(&self) -> &'static str {
        ENGINE_NAME
    }

    fn prepare(
        &self,
        source: &Source,
        ctx: &PrepareContext<'_>,
    ) -> Result<PreparedSource, EngineError> {
        let block = source
            .helmfile
            .as_ref()
            .expect("dispatch ensures helmfile block");
        let helmfile_path = PathBuf::from(&block.path);
        let chart_dir = ctx.work_dir.join(&source.name);
        let templates_dir = chart_dir.join("templates");

        std::fs::create_dir_all(&templates_dir).map_err(|e| EngineError::Write {
            engine: ENGINE_NAME,
            path: templates_dir.clone(),
            source: e,
        })?;

        let output = Command::new("helmfile")
            .arg("--file")
            .arg(&helmfile_path)
            .arg("template")
            .output()
            .map_err(|source| EngineError::Spawn {
                engine: ENGINE_NAME,
                cmd: format!("helmfile --file {} template", helmfile_path.display()),
                source,
            })?;

        if !output.status.success() {
            return Err(EngineError::CliFailed {
                engine: ENGINE_NAME,
                cmd: "helmfile template".to_string(),
                status: output.status.code().unwrap_or(-1),
                stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
            });
        }

        write(templates_dir.join("rendered.yaml"), &output.stdout)?;

        let chart_yaml = ChartYaml {
            api_version: "v2".to_string(),
            name: source.name.clone(),
            version: block.version.clone(),
            description: Some("Auto-generated by akua from a helmfile source".to_string()),
            chart_type: Some("application".to_string()),
            dependencies: Vec::new(),
        };
        let chart_yaml_bytes =
            serde_yaml::to_string(&chart_yaml).expect("ChartYaml serializes to YAML");
        write(chart_dir.join("Chart.yaml"), chart_yaml_bytes.as_bytes())?;

        Ok(PreparedSource::LocalChart(chart_dir))
    }
}

fn write(path: PathBuf, bytes: &[u8]) -> Result<(), EngineError> {
    std::fs::write(&path, bytes).map_err(|e| EngineError::Write {
        engine: ENGINE_NAME,
        path,
        source: e,
    })
}

pub(crate) static HELMFILE_ENGINE: HelmfileEngine = HelmfileEngine;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::HelmfileBlock;

    #[test]
    fn spawn_failure_on_missing_binary() {
        // Can't easily test the happy path without helmfile on PATH, but we
        // can at least confirm the engine errors sensibly when invoked with
        // a non-existent helmfile and no `helmfile` binary (or even with
        // one — it'll fail on the missing file).
        let tmp = tempfile::tempdir().unwrap();
        let s = Source {
            name: "stack".to_string(),
            helm: None,
            kcl: None,
            helmfile: Some(HelmfileBlock {
                path: "/does/not/exist.yaml".to_string(),
                version: "0.1.0".to_string(),
            }),
            values: None,
        };
        let ctx = PrepareContext {
            work_dir: tmp.path(),
        };
        let result = HelmfileEngine.prepare(&s, &ctx);
        // Either spawn fails (no binary) or the CLI errors (missing file).
        assert!(
            matches!(
                result,
                Err(EngineError::Spawn { .. }) | Err(EngineError::CliFailed { .. })
            ),
            "unexpected result: {result:?}",
        );
    }
}
