//! KCL engine — native Rust via `kcl-lang` (the official SDK).
//!
//! Source shape:
//!
//! ```yaml
//! sources:
//!   - name: app
//!     kcl:
//!       entrypoint: ./app.k
//!       version: 0.1.0
//! ```
//!
//! The engine evaluates the `.k` entrypoint, writes the rendered YAML into
//! `<work_dir>/<source.name>/templates/rendered.yaml`, and emits a
//! `Chart.yaml` so downstream umbrella assembly treats the output as a
//! normal Helm subchart.

use std::path::{Path, PathBuf};

use super::{Engine, EngineError, PrepareContext, PreparedSource};
use crate::source::Source;
use crate::umbrella::ChartYaml;

pub const ENGINE_NAME: &str = "kcl";

#[derive(Debug, Clone, Default)]
pub struct KclEngine;

impl Engine for KclEngine {
    fn name(&self) -> &'static str {
        ENGINE_NAME
    }

    fn prepare(
        &self,
        source: &Source,
        ctx: &PrepareContext<'_>,
    ) -> Result<PreparedSource, EngineError> {
        let block = source.kcl.as_ref().expect("dispatch ensures kcl block");
        let entrypoint = PathBuf::from(&block.entrypoint);
        let source_bytes = std::fs::read(&entrypoint).map_err(|e| EngineError::Write {
            engine: ENGINE_NAME,
            path: entrypoint.clone(),
            source: e,
        })?;
        let source_code = String::from_utf8(source_bytes).map_err(|_| EngineError::Write {
            engine: ENGINE_NAME,
            path: entrypoint.clone(),
            source: std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "KCL source is not valid UTF-8",
            ),
        })?;

        let rendered = eval_kcl(&entrypoint, &source_code)?;

        let chart_dir = ctx.work_dir.join(&source.name);
        let templates_dir = chart_dir.join("templates");
        std::fs::create_dir_all(&templates_dir).map_err(|e| EngineError::Write {
            engine: ENGINE_NAME,
            path: templates_dir.clone(),
            source: e,
        })?;
        std::fs::write(templates_dir.join("rendered.yaml"), rendered.as_bytes()).map_err(|e| {
            EngineError::Write {
                engine: ENGINE_NAME,
                path: templates_dir.join("rendered.yaml"),
                source: e,
            }
        })?;

        let chart_yaml = ChartYaml {
            api_version: "v2".to_string(),
            name: source.name.clone(),
            version: block.version.clone(),
            description: Some("Auto-generated by akua from a KCL source".to_string()),
            chart_type: Some("application".to_string()),
            dependencies: Vec::new(),
        };
        let chart_yaml_str =
            serde_yaml::to_string(&chart_yaml).expect("ChartYaml serializes deterministically");
        std::fs::write(chart_dir.join("Chart.yaml"), chart_yaml_str).map_err(|e| {
            EngineError::Write {
                engine: ENGINE_NAME,
                path: chart_dir.join("Chart.yaml"),
                source: e,
            }
        })?;

        Ok(PreparedSource::LocalChart(chart_dir))
    }
}

fn eval_kcl(filename: &Path, code: &str) -> Result<String, EngineError> {
    use kcl_lang::{ExecProgramArgs, API};

    let api = API::default();
    let args = ExecProgramArgs {
        k_filename_list: vec![filename.to_string_lossy().into_owned()],
        k_code_list: vec![code.to_string()],
        ..Default::default()
    };
    match api.exec_program(&args) {
        Ok(result) => {
            if !result.err_message.is_empty() {
                return Err(EngineError::CliFailed {
                    engine: ENGINE_NAME,
                    cmd: "kcl-lang exec_program".to_string(),
                    status: 1,
                    stderr: result.err_message,
                });
            }
            Ok(result.yaml_result)
        }
        Err(e) => Err(EngineError::CliFailed {
            engine: ENGINE_NAME,
            cmd: "kcl-lang exec_program".to_string(),
            status: -1,
            stderr: e.to_string(),
        }),
    }
}

pub(crate) static KCL_ENGINE: KclEngine = KclEngine;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::KclBlock;

    fn kcl_source(name: &str, entrypoint: &str) -> Source {
        Source {
            name: name.to_string(),
            helm: None,
            kcl: Some(KclBlock {
                entrypoint: entrypoint.to_string(),
                version: "0.1.0".to_string(),
            }),
            helmfile: None,
            values: None,
        }
    }

    #[test]
    fn missing_entrypoint_errors() {
        let tmp = tempfile::tempdir().unwrap();
        let s = kcl_source("empty", "/does/not/exist.k");
        let ctx = PrepareContext {
            work_dir: tmp.path(),
        };
        let err = KclEngine.prepare(&s, &ctx).unwrap_err();
        assert!(matches!(err, EngineError::Write { .. }));
    }

    #[test]
    fn renders_simple_kcl_program() {
        let tmp = tempfile::tempdir().unwrap();
        let k_file = tmp.path().join("t.k");
        std::fs::write(&k_file, "a = 1\nb = a + 2\n").unwrap();
        let s = kcl_source("t", k_file.to_str().unwrap());
        let ctx = PrepareContext {
            work_dir: tmp.path(),
        };
        let result = KclEngine.prepare(&s, &ctx).unwrap();
        match result {
            PreparedSource::LocalChart(path) => {
                let yaml = std::fs::read_to_string(path.join("templates/rendered.yaml")).unwrap();
                assert!(yaml.contains("a: 1"));
                assert!(yaml.contains("b: 3"));
            }
            other => panic!("expected LocalChart, got {other:?}"),
        }
    }
}
