//! KCL engine — native Rust via `kcl-lang` (the official Rust SDK from
//! [`kcl-lang/lib`](https://github.com/kcl-lang/lib)).
//!
//! No subprocess, no fetch, no `kcl` binary on `$PATH` — just a Rust crate
//! call that evaluates the `.k` program and returns rendered YAML. This is
//! the CLI default; `engine-kcl-wasm` exists for the browser path where
//! heavy Rust deps can't compile to wasm32.
//!
//! Source shape is identical to the wasm variant:
//!
//! ```yaml
//! sources:
//!   - id: app
//!     engine: kcl
//!     chart:
//!       repoUrl: file://./app.k
//!       targetRevision: 0.1.0
//! ```
//!
//! ## Trade-offs
//!
//! - **+** Fast (~4 ms per eval vs ~1 s wasmtime JIT).
//! - **+** 12 MB native bin vs 22 MB (wasmtime + kcl.wasm).
//! - **+** Zero ambient authority — no `$PATH` lookup, no env leakage.
//! - **−** First compile ~3.5 min (deps are heavy; cached thereafter).
//! - **−** Doesn't cross-compile to wasm32 for `akua-wasm`.

use std::path::PathBuf;

use super::{Engine, EngineError, PrepareContext, PreparedSource};
use crate::source::HelmSource;
use crate::umbrella::ChartYaml;

pub const ENGINE_NAME: &str = "kcl";

#[derive(Debug, Clone, Default)]
pub struct KclEngine;

impl Engine for KclEngine {
    fn name(&self) -> &'static str {
        ENGINE_NAME
    }

    fn prepare(
        &self,
        source: &HelmSource,
        ctx: &PrepareContext<'_>,
    ) -> Result<PreparedSource, EngineError> {
        let entrypoint = resolve_entrypoint(source)?;
        let source_bytes = std::fs::read(&entrypoint).map_err(|e| EngineError::Write {
            engine: ENGINE_NAME,
            path: entrypoint.clone(),
            source: e,
        })?;
        let source_code = String::from_utf8(source_bytes).map_err(|_| EngineError::Write {
            engine: ENGINE_NAME,
            path: entrypoint.clone(),
            source: std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "KCL source is not valid UTF-8",
            ),
        })?;

        let rendered = eval_kcl(&entrypoint, &source_code)?;

        let source_id = source.id.clone().unwrap_or_else(|| "kcl-source".to_string());
        let chart_dir = ctx.work_dir.join(&source_id);
        let templates_dir = chart_dir.join("templates");
        std::fs::create_dir_all(&templates_dir).map_err(|e| EngineError::Write {
            engine: ENGINE_NAME,
            path: templates_dir.clone(),
            source: e,
        })?;
        std::fs::write(templates_dir.join("rendered.yaml"), rendered.as_bytes()).map_err(|e| {
            EngineError::Write {
                engine: ENGINE_NAME,
                path: templates_dir.join("rendered.yaml"),
                source: e,
            }
        })?;

        let chart_yaml = ChartYaml {
            api_version: "v2".to_string(),
            name: source_id,
            version: source.chart.target_revision.clone(),
            description: Some("Auto-generated by akua from a KCL source".to_string()),
            chart_type: Some("application".to_string()),
            dependencies: Vec::new(),
        };
        let chart_yaml_str =
            serde_yaml::to_string(&chart_yaml).expect("ChartYaml serializes deterministically");
        std::fs::write(chart_dir.join("Chart.yaml"), chart_yaml_str).map_err(|e| {
            EngineError::Write {
                engine: ENGINE_NAME,
                path: chart_dir.join("Chart.yaml"),
                source: e,
            }
        })?;

        Ok(PreparedSource::LocalChart(chart_dir))
    }
}

fn eval_kcl(filename: &std::path::Path, code: &str) -> Result<String, EngineError> {
    use kcl_lang::{ExecProgramArgs, API};

    let api = API::default();
    let args = ExecProgramArgs {
        k_filename_list: vec![filename.to_string_lossy().into_owned()],
        k_code_list: vec![code.to_string()],
        ..Default::default()
    };
    match api.exec_program(&args) {
        Ok(result) => {
            if !result.err_message.is_empty() {
                return Err(EngineError::CliFailed {
                    engine: ENGINE_NAME,
                    cmd: "kcl-lang exec_program".to_string(),
                    status: 1,
                    stderr: result.err_message,
                });
            }
            Ok(result.yaml_result)
        }
        Err(e) => Err(EngineError::CliFailed {
            engine: ENGINE_NAME,
            cmd: "kcl-lang exec_program".to_string(),
            status: -1,
            stderr: e.to_string(),
        }),
    }
}

fn resolve_entrypoint(source: &HelmSource) -> Result<PathBuf, EngineError> {
    let raw = if !source.chart.repo_url.is_empty() {
        source.chart.repo_url.as_str()
    } else if let Some(p) = source.chart.path.as_deref() {
        p
    } else {
        return Err(EngineError::MissingField {
            engine: ENGINE_NAME,
            source_id: source.id.clone().unwrap_or_default(),
            field: "chart.repoUrl or chart.path (KCL entrypoint file)",
        });
    };
    let stripped = raw.strip_prefix("file://").unwrap_or(raw);
    Ok(PathBuf::from(stripped))
}

pub(crate) static KCL_ENGINE: KclEngine = KclEngine;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::ChartRef;

    #[test]
    fn missing_entrypoint_errors() {
        let tmp = tempfile::tempdir().unwrap();
        let s = HelmSource {
            id: Some("empty".to_string()),
            engine: Some("kcl".to_string()),
            chart: ChartRef {
                repo_url: "".to_string(),
                chart: None,
                target_revision: "0.1.0".to_string(),
                path: None,
            },
            values: None,
        };
        let ctx = PrepareContext { work_dir: tmp.path() };
        let err = KclEngine.prepare(&s, &ctx).unwrap_err();
        assert!(matches!(err, EngineError::MissingField { .. }));
    }

    #[test]
    fn renders_simple_kcl_program() {
        let tmp = tempfile::tempdir().unwrap();
        let k_file = tmp.path().join("t.k");
        std::fs::write(&k_file, "a = 1\nb = a + 2\n").unwrap();
        let s = HelmSource {
            id: Some("t".to_string()),
            engine: Some("kcl".to_string()),
            chart: ChartRef {
                repo_url: format!("file://{}", k_file.display()),
                chart: None,
                target_revision: "0.1.0".to_string(),
                path: None,
            },
            values: None,
        };
        let ctx = PrepareContext { work_dir: tmp.path() };
        let result = KclEngine.prepare(&s, &ctx).unwrap();
        match result {
            PreparedSource::LocalChart(path) => {
                let yaml = std::fs::read_to_string(path.join("templates/rendered.yaml")).unwrap();
                assert!(yaml.contains("a: 1"));
                assert!(yaml.contains("b: 3"));
            }
            other => panic!("expected LocalChart, got {other:?}"),
        }
    }
}
