//! KCL engine — runs the `kcl` CLI to evaluate a `.k` program, captures the
//! rendered Kubernetes YAML, and wraps it as a static Helm chart dir.
//!
//! Source shape:
//!
//! ```yaml
//! sources:
//!   - id: app
//!     engine: kcl
//!     chart:
//!       repoUrl: file://./app.k      # path to the .k entrypoint
//!       targetRevision: 0.1.0        # chart version for the output
//! ```
//!
//! The entrypoint is read from `chart.repo_url` (treating `file://` prefix as
//! optional) or `chart.path`. The chart version is `chart.target_revision`.
//! The chart name is `source.id`.
//!
//! Output is an "early-binding" static chart: `Chart.yaml` + a single
//! `templates/rendered.yaml` containing the KCL output. No late-bindable
//! templates — customers can't `--set` values post-build.
//!
//! Requires `kcl` on `$PATH`. Pin the version via `mise`.

use std::path::PathBuf;
use std::process::Command;

use super::{Engine, EngineError, PrepareContext, PreparedSource};
use crate::source::HelmSource;
use crate::umbrella::ChartYaml;

#[derive(Debug, Clone, Default)]
pub struct KclEngine;

impl Engine for KclEngine {
    fn name(&self) -> &'static str {
        "kcl"
    }

    fn prepare(
        &self,
        source: &HelmSource,
        ctx: &PrepareContext<'_>,
    ) -> Result<PreparedSource, EngineError> {
        let entrypoint = resolve_entrypoint(source)?;
        let source_id = source.id.clone().unwrap_or_else(|| "kcl-source".to_string());
        let chart_dir = ctx.work_dir.join(&source_id);
        let templates_dir = chart_dir.join("templates");

        std::fs::create_dir_all(&templates_dir).map_err(|e| EngineError::Write {
            engine: "kcl",
            path: templates_dir.clone(),
            source: e,
        })?;

        let output = Command::new("kcl")
            .arg("run")
            .arg(&entrypoint)
            .output()
            .map_err(|source| EngineError::Spawn {
                engine: "kcl",
                cmd: format!("kcl run {}", entrypoint.display()),
                source,
            })?;

        if !output.status.success() {
            return Err(EngineError::CliFailed {
                engine: "kcl",
                cmd: "kcl run".to_string(),
                status: output.status.code().unwrap_or(-1),
                stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
            });
        }

        write(
            templates_dir.join("rendered.yaml"),
            &output.stdout,
        )?;

        let chart_yaml = ChartYaml {
            api_version: "v2".to_string(),
            name: source_id,
            version: source.chart.target_revision.clone(),
            description: Some("Auto-generated by akua from a KCL source".to_string()),
            chart_type: Some("application".to_string()),
            dependencies: Vec::new(),
        };
        let chart_yaml_bytes =
            serde_yaml::to_string(&chart_yaml).expect("ChartYaml serializes to YAML");
        write(chart_dir.join("Chart.yaml"), chart_yaml_bytes.as_bytes())?;

        Ok(PreparedSource::LocalChart(chart_dir))
    }
}

fn resolve_entrypoint(source: &HelmSource) -> Result<PathBuf, EngineError> {
    let raw = if !source.chart.repo_url.is_empty() {
        source.chart.repo_url.as_str()
    } else if let Some(p) = source.chart.path.as_deref() {
        p
    } else {
        return Err(EngineError::MissingField {
            engine: "kcl",
            source_id: source.id.clone().unwrap_or_default(),
            field: "chart.repoUrl or chart.path (KCL entrypoint file)",
        });
    };
    let stripped = raw.strip_prefix("file://").unwrap_or(raw);
    Ok(PathBuf::from(stripped))
}

fn write(path: PathBuf, bytes: &[u8]) -> Result<(), EngineError> {
    std::fs::write(&path, bytes).map_err(|e| EngineError::Write {
        engine: "kcl",
        path,
        source: e,
    })
}

pub(crate) static KCL_ENGINE: KclEngine = KclEngine;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::ChartRef;

    fn src(entry: &str) -> HelmSource {
        HelmSource {
            id: Some("my-app".to_string()),
            engine: Some("kcl".to_string()),
            chart: ChartRef {
                repo_url: format!("file://{entry}"),
                chart: None,
                target_revision: "0.1.0".to_string(),
                path: None,
            },
            values: None,
        }
    }

    #[test]
    fn missing_kcl_binary_surfaces_spawn_error() {
        let tmp = tempfile::tempdir().unwrap();
        // Write a trivial KCL file (we don't care about its contents — kcl
        // binary won't exist in most CI environments).
        let k = tmp.path().join("app.k");
        std::fs::write(&k, "foo = 1\n").unwrap();
        let s = src(k.to_str().unwrap());
        let ctx = PrepareContext { work_dir: tmp.path() };

        let engine = KclEngine;
        let result = engine.prepare(&s, &ctx);
        // Either kcl isn't installed → Spawn, or it is installed and we get
        // CliFailed or Ok. All three are legitimate; the trait contract is
        // satisfied.
        match result {
            Ok(PreparedSource::LocalChart(_)) => {}
            Err(EngineError::Spawn { .. }) => {}
            Err(EngineError::CliFailed { .. }) => {}
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn missing_entrypoint_errors() {
        let tmp = tempfile::tempdir().unwrap();
        let s = HelmSource {
            id: Some("empty".to_string()),
            engine: Some("kcl".to_string()),
            chart: ChartRef {
                repo_url: "".to_string(),
                chart: None,
                target_revision: "0.1.0".to_string(),
                path: None,
            },
            values: None,
        };
        let ctx = PrepareContext { work_dir: tmp.path() };
        let err = KclEngine.prepare(&s, &ctx).unwrap_err();
        assert!(matches!(err, EngineError::MissingField { engine: "kcl", .. }));
    }
}
