// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which env var triggered agent detection. Recorded in `akua whoami`
 * output for introspection and in debug-level logs for post-hoc diagnosis.
 */
export type AgentSource = "agent" | "claude_code" | "gemini_cli" | "cursor_cli" | "akua_agent";
