// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSource } from "./AgentSource";

/**
 * Result of agent-context detection at process start.
 *
 * When `detected == true`, the CLI layer should (per §1.5) auto-enable
 * `--json`, `--log=json`, `--no-color`, `--no-progress`, `--no-interactive`.
 * Explicit user flags win over these defaults.
 */
export type AgentContext = { detected: boolean, 
/**
 * Which env var surfaced the agent (present iff `detected`).
 */
source: AgentSource | null, 
/**
 * The value of the detected env var (e.g. `"goose"` for `AGENT=goose`).
 * For bool-style markers (`CLAUDECODE=1`) this is the raw string.
 */
name: string | null, 
/**
 * Whether detection was disabled via `AKUA_NO_AGENT_DETECT=1`.
 */
disabled_via_env: boolean, };
