// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckResult } from "./CheckResult";

/**
 * Output shape for `akua check --json`. The `status` field is
 * `"ok"` iff every entry in `checks` has `ok == true`.
 */
export type CheckOutput = { status: string, checks: Array<CheckResult>, };
