// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LintIssue } from "./LintIssue";

export type CheckResult = { 
/**
 * Short label for the check: `"manifest"`, `"lockfile"`,
 * `"package"`.
 */
name: string, ok: boolean, 
/**
 * One-line error from the failing check; `null` when `ok`.
 */
error: string | null, 
/**
 * Per-file issues from linting the Package.k. Other check kinds
 * leave this empty. Always serialized (possibly empty) so
 * consumers can iterate without a presence guard.
 */
issues: Array<LintIssue>, };
