// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LintIssue } from "./LintIssue";

export type CheckResult = { 
/**
 * Short label for the check: `"manifest"`, `"lockfile"`,
 * `"package"`.
 */
name: string, ok: boolean, 
/**
 * One-line error from the failing check; absent when `ok`.
 * `#[serde(default)]` is load-bearing for the JSON Schema:
 * it tells schemars the field is optional.
 */
error?: string | null, 
/**
 * Per-file issues from linting the Package.k. Other check kinds
 * leave this empty.
 */
issues?: Array<LintIssue>, };
