// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LockedInfo } from "./LockedInfo";

export type DepRow = { name: string, 
/**
 * `"oci"` / `"git"` / `"path"` / `"unknown"`.
 */
source: string, 
/**
 * The actual ref recorded in `akua.toml`.
 */
source_ref: string, 
/**
 * `#[serde(default)]` is load-bearing for the JSON Schema:
 * it tells schemars the field is optional, which the
 * generated schema enforces. Without it, `skip_serializing_if`
 * alone produces output that schemars rejects as missing a
 * required field.
 */
version?: string | null, 
/**
 * Lockfile row, present only when `akua.lock` exists and contains
 * a matching entry.
 */
locked?: LockedInfo | null, };
