// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

/**
 * Structural diff between two directory trees. All paths are
 * relative to the respective root; sorted alphabetically for
 * deterministic output.
 */
export type DirDiff = { 
/**
 * Files present in the `after` root but not the `before` root.
 */
added: Array<string>, 
/**
 * Files present in the `before` root but not the `after` root.
 */
removed: Array<string>, 
/**
 * Files present in both but with differing sha256 content.
 */
changed: Array<FileChange>, 
/**
 * Files present in both with identical sha256 content.
 */
unchanged?: Array<string>, 
/**
 * Entries that aren't regular files (symlinks, fifos, sockets…).
 * Surfaced so the caller knows the diff isn't exhaustive, without
 * the diff itself trying to semantically compare those kinds.
 */
skipped?: Array<string>, };
