// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The seven typed exit codes every akua verb may produce.
 *
 * Agents branch on these. Humans read them. The stability contract is
 * that meanings never change; new codes require a major version bump.
 *
 * Serialized as the stable kebab-case name (`"success"`, `"user-error"`,
 * `"policy-deny"`, etc.) — same string [`ExitCode::name`] returns. The
 * SDK maps from the numeric `child.exitCode` (0..=6) to this name.
 */
export type ExitCode = "success" | "user-error" | "system-error" | "policy-deny" | "rate-limited" | "needs-approval" | "timeout";
