// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileChange = { path: string, 
/**
 * `sha256:<hex>` of the `before` file's contents.
 */
before: string, 
/**
 * `sha256:<hex>` of the `after` file's contents.
 */
after: string, };
