// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LintIssue } from "./LintIssue";

export type LintOutput = { 
/**
 * `"ok"` when no issues reported; `"fail"` otherwise.
 */
status: string, issues: Array<LintIssue>, };
