// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single `option()` call-site in a parsed Package, surfaced for
 * inspection without executing the program. Mirrors kcl_lang's
 * `OptionHelp` shape with idiomatic Rust optionals.
 */
export type OptionInfo = { 
/**
 * The option key (first argument to `option("…")`).
 */
name: string, 
/**
 * The declared type of the binding receiving the option — e.g.
 * `"Input"` for `input: Input = option("input") or Input {}`.
 * Empty when the option is used without a type annotation.
 */
type?: string, required: boolean, 
/**
 * Default value (literal form) when the option call includes one.
 */
default?: string | null, 
/**
 * `help="…"` text attached to the option call, surfaced in docs
 * tooling; absent when the authoring site didn't provide any.
 */
help?: string | null, };
