// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionInfo } from "./OptionInfo";

export type PackageInspectBody = { path: string, options: Array<OptionInfo>, };
