// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verdict for a single render: where manifests went, how many, and a
 * hash that makes "did the rendered output change?" a byte comparison.
 */
export type RenderSummary = { format: string, 
/**
 * Directory the manifests were written into (or would be, on
 * `--dry-run`). Absolute or relative depending on the `out_root`
 * the caller passed.
 */
target: string, manifests: number, 
/**
 * `sha256:<hex>` of the concatenated `<filename>\n<yaml>` blocks.
 * Filename participates in the hash so two identical resources
 * routed to different filenames produce different hashes.
 */
hash: string, 
/**
 * Relative filenames, in write order. Empty vec is serialized as
 * omitted to keep the JSON shape tight.
 */
files: Array<string>, };
