// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

/**
 * The canonical error shape. One struct; every verb reuses it.
 *
 * `code` is the stable, load-bearing identifier. `message` is the one-line
 * summary. The rest are optional pointers — a file path, a field name, a
 * suggestion, a docs URL.
 */
export type StructuredError = { 
/**
 * Log level. Always `"error"` for hard failures; `"warn"` for
 * recoverable issues emitted alongside a success exit.
 */
level: Level, 
/**
 * Stable, machine-readable identifier (SHOUTY_SNAKE_CASE).
 * Example: `E_SCHEMA_INVALID`, `E_OCI_DIGEST_MISMATCH`.
 */
code: string, 
/**
 * Human-readable one-line summary.
 */
message: string, 
/**
 * File path, OCI ref, or resource identifier the error refers to.
 */
path?: string | null, 
/**
 * Dotted field path inside `path` when the error is field-specific.
 * Example: `spec.replicas`, `metadata.labels.team`.
 */
field?: string | null, 
/**
 * 1-based line number in `path` when applicable.
 */
line?: number | null, 
/**
 * Actionable suggestion — a one-liner the caller can apply.
 * Absent when there's no generic fix.
 */
suggestion?: string | null, 
/**
 * URL to the error's documentation page. Convention:
 * `https://akua.dev/errors/<CODE>`.
 */
docs?: string | null, 
/**
 * Machine-executable recovery steps. Agents can use these to fix
 * the error programmatically. Each entry is a complete command.
 */
next_actions?: Array<string>, };
