// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepRow } from "./DepRow";
import type { PackageInfo } from "./PackageInfo";

export type TreeOutput = { package: PackageInfo, dependencies: Array<DepRow>, };
