// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Summary } from "./Summary";
import type { Violation } from "./Violation";

/**
 * Verify verdict JSON shape. Stable across releases.
 */
export type VerifyOutput = { 
/**
 * `"ok"` when everything checks out; `"fail"` otherwise. Derived
 * from `violations.is_empty()`.
 */
status: string, summary: Summary, 
/**
 * Structured violations. Empty when `status == "ok"`.
 */
violations: Array<Violation>, };
