// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Version response shape.
 */
export type VersionOutput = { 
/**
 * Semver version of the `akua` binary.
 */
version: string, };
