apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
